import { app } from 'electron'
import * as path from 'path'
import * as crypto from 'crypto'
import { getAria2ProcessManager } from '../managers/Aria2ProcessManager'
import type { Aria2ProcessManager } from '../managers/Aria2ProcessManager'
import { WindowController } from './WindowController'
import { registerSecureHandler } from '../utils/ipcSecurity'
import { callAria2Rpc } from '../utils/aria2Rpc'
import { getSettingsFresh, saveSettings } from '../utils/settingsAccessor'
// 注意：主进程产物是 CJS，运行时无法解析 @/ 别名，必须用相对路径引入 src/shared
import { isLocalEngineAddress } from '../../src/shared/localEngine'
import { createLogger } from '../utils/logger'
import type { AppSettings } from '../types/store'

const logger = createLogger('Aria2Controller')

/** 端口号合法范围（1024 以下为系统保留端口，65535 为上限） */
const MIN_PORT = 1024
const MAX_PORT = 65535

export class Aria2Controller {
  private aria2Manager: Aria2ProcessManager | null = null
  private windowController: WindowController
  /**
   * 供 ipcSecurity 工厂使用的窗口取值器（口径与原 validateSender 一致，
   * 延迟到事件触发时才取主窗口，故构造期 windowController 字段尚未赋值也无影响）
   */
  private windowRef = () => this.windowController.getMainWindow()

  /**
   * 是否已请求过 aria2 优雅关闭。
   * 置位后 aria2 会自行保存会话并退出，此时进程退出兜底**不应**再强杀它（会截断正在写的会话文件）。
   */
  private shutdownRequested = false

  /** 注：本类不再持有 store —— settings 读写统一走 utils/settingsAccessor */
  constructor(windowController: WindowController) {
    this.windowController = windowController

    /**
     * 退出兜底：回收 aria2，避免主进程异常退出后留下孤儿进程占住 RPC 端口。
     *
     * 为什么需要：Windows 不会因父进程退出而回收子进程，而"崩溃"与 `app.exit()` 都不经过 before-quit，
     * 没有这条兜底时 aria2 会继续在后台跑着，导致下次启动引擎因端口占用失败。
     *
     * 为什么可行：`process.on('exit')` 里只能做同步操作，而 `child.kill()` 恰好是同步发信号。
     * 两种情况明确跳过（都由 killIfRunning 与 shutdownRequested 处理）：
     * - 已请求优雅关闭（aria2 正在自行保存会话并退出）；
     * - 正在停止过程中（manager 内部按 isStopping 判断）。
     *
     * 本类在 main.ts 中只实例化一次，因此不会累积多个 exit 监听。
     */
    process.on('exit', () => {
      if (this.shutdownRequested) return
      this.aria2Manager?.killIfRunning()
    })
  }

  public async initialize() {
    try {
      // 直读：此处要取"当前权威密钥"，作为后续自动生成 / 从 conf 回填判定的基准，
      // 不能使用可能滞后的缓存值
      const settings = getSettingsFresh()
      const aria2Settings = settings.aria2 || {}

      const settingsSecret = String(aria2Settings.secret || '')
      const localPort = Number(aria2Settings.port) || 6800

      const aria2Config = {
        port: localPort,
        secret: settingsSecret,
        downloadDir: aria2Settings.downloadDir ? String(aria2Settings.downloadDir) : app.getPath('downloads'),
        autoStart: aria2Settings.autoStart !== undefined ? Boolean(aria2Settings.autoStart) : true
      }

      this.aria2Manager = getAria2ProcessManager(aria2Config)

      /**
       * 密钥权威来源是 aria2.conf 中的 rpc-secret —— 它才决定 aria2 是否要求 token。
       * settings 与 conf 可能因以下原因不同步：
       *  - 导入设置（导出时密钥脱敏为 ***，导入时清空为 ''）
       *  - 用户手工编辑 aria2.conf
       * 此时若只信任 settings，会出现"aria2 要求 token 而前端不带 token"→ 连接失败。
       * 因此 conf 有值时一律以 conf 为准，回填 settings 与本地连接预设。
       */
      const confSecret = String(this.aria2Manager.getConfig().secret || '')

      /**
       * conf 与 settings 都没有密钥、且用户从未显式管理过密钥时，自动生成随机 secret（仅一次）。
       * 背景：默认配置 rpc-allow-origin-all=true（渲染层 file:// 的 null origin 跨源
       * 访问 localhost RPC 依赖它）+ 无密钥时，用户浏览器中的任意恶意网页可通过 CORS
       * 直接调用本机 aria2 RPC（addUri 指定 dir/out 写任意文件等）。
       * 用户在设置页显式保存过密钥配置（含主动清空）后 secretAutogenerated=false，
       * 尊重"无密钥"的显式选择，不再自动生成。
       */
      let secret = confSecret || settingsSecret
      let secretGenerated = false
      if (!secret && !aria2Settings.secretAutogenerated) {
        secret = crypto.randomBytes(16).toString('hex')
        secretGenerated = true
        logger.info('已自动生成 aria2 RPC secret（防止浏览器跨源调用本机 RPC）')
      }

      // 日志脱敏：不打印 RPC secret
      logger.info('初始化 Aria2，配置：', {
        port: aria2Config.port,
        downloadDir: aria2Config.downloadDir,
        autoStart: aria2Config.autoStart,
        secret: secret ? '***' : ''
      })

      // conf 缺密钥时才写回（conf 有值时 secret === confSecret，天然不会覆盖用户手工配置）
      if (secret !== confSecret) {
        this.aria2Manager.updateConfig({ secret })
        // 立即落盘：默认微任务合批会延迟到 spawn 之后，需确保 aria2 启动时读到含密钥的配置
        this.aria2Manager.flushConfig()
      }

      // settings 与最终密钥不一致（新生成 / 从 conf 回填）时同步应用设置（加密落盘）
      if (secret !== settingsSecret) {
        const currentSettings = getSettingsFresh()
        /**
         * 渲染层实际用「连接预设(connectionProfiles)」中的 secret 连接，而不是 settings.aria2.secret。
         * 因此密钥变更后必须让指向本机引擎的预设与之一致，否则前端会连不上本地引擎。
         * 仅处理"本机地址 + 当前端口"的预设（用户自建的远程预设一律不动）：
         * 空值补齐、旧值对齐，保证一轮启动后 conf / settings / 预设三者一致。
         * 判定口径与渲染层共用 src/shared/localEngine，避免两侧分叉。
         */
        const updatedProfiles = currentSettings.connectionProfiles?.map(p => {
          if (!p?.config) return p
          if (!isLocalEngineAddress(p.config.host, p.config.port, aria2Config.port)) return p
          if (p.config.secret === secret) return p
          return { ...p, config: { ...p.config, secret } }
        })

        const updatedSettings: AppSettings = {
          ...currentSettings,
          aria2: {
            ...currentSettings.aria2,
            host: 'localhost',
            port: aria2Config.port,
            protocol: 'http',
            path: '/jsonrpc',
            secret,
            // 仅"本次由应用生成"时置 true；从 conf 回填时保持用户原有标记语义
            secretAutogenerated: secretGenerated ? true : aria2Settings.secretAutogenerated
          }
        }
        // 仅在确有预设被同步时写该字段：避免在没有预设的 store 中写入显式 undefined 键，
        // 干扰渲染层 mergeWithDefaults 对默认预设的回退
        if (updatedProfiles) {
          updatedSettings.connectionProfiles = updatedProfiles
        }
        // 写入口统一走 settingsAccessor：它负责加密落盘并同步刷新缓存（写与失效原子化）
        saveSettings(updatedSettings)
      }

      /**
       * 注入优雅关闭钩子：所有停止/重启路径（手动停止、配置变更触发的自动重启、退出应用）
       * 都先经 RPC 让 aria2 落盘，再退出进程——Windows 上直接发信号是强杀（TerminateProcess），
       * 不会给 aria2 保存会话的机会。
       *
       * 分两步而不是只调 aria2.shutdown：
       * aria2 收到 shutdown 后会**立即断开连接并退出**，客户端往往收不到响应而判为失败
       * （连接被重置 / 等待超时）；一旦判为失败，stop() 会回退为 SIGTERM 强杀，会话就再也保存不下来了。
       * 会话没保存的后果很具体：下次启动按 `input-file` + `continue=true` 恢复未完成任务，
       * 再次完成后**又触发一次"下载完成"通知与动作**（用户看到的是"重启后又通知一遍、又退出一遍"）。
       * 因此先显式 saveSession 落盘，再请求关闭——这样会话是否保住就与 shutdown 的响应无关了。
       */
      this.aria2Manager.setGracefulShutdown(async () => {
        const { port, secret } = this.getRpcSettings()

        // 第一步：显式保存会话（幂等；这是会正常返回的普通 RPC，比 shutdown 可靠）
        const saveStartedAt = Date.now()
        try {
          await callAria2Rpc({ port, secret, method: 'aria2.saveSession', timeoutMs: 2000 })
          logger.info(`已保存 aria2 会话（RPC 耗时 ${Date.now() - saveStartedAt}ms）`)
        } catch (error) {
          // 保存失败不阻断关闭流程，但必须留痕：这意味着本次退出会丢掉未完成的任务进度
          logger.warn(
            `保存 aria2 会话失败（耗时 ${Date.now() - saveStartedAt}ms），本次退出可能丢失未完成任务：`,
            error
          )
        }

        // 第二步：请求 aria2 关闭（会话此时已落盘）
        const shutdownStartedAt = Date.now()
        try {
          await callAria2Rpc({ port, secret, method: 'aria2.shutdown', timeoutMs: 3000 })
          logger.info(`已请求 aria2 关闭（RPC 耗时 ${Date.now() - shutdownStartedAt}ms）`)
        } catch (error) {
          logger.warn(`请求 aria2 关闭失败（耗时 ${Date.now() - shutdownStartedAt}ms）：`, error)
          throw error
        }
      })

      if (aria2Config.autoStart) {
        const success = await this.aria2Manager.start()
        logger.info(`Aria2 自动启动结果: ${success}`)
        if (!success) {
          // 附带 aria2 stderr，让错误弹窗能展示 aria2 自身的报错（端口占用/坏配置/杀软拦截等）
          const stderr = this.aria2Manager.getLastStderr()
          throw new Error(stderr
            ? `Aria2 进程启动失败，请检查可执行文件与配置。\n\nAria2 输出:\n${stderr}`
            : 'Aria2 进程启动失败，请检查可执行文件与配置')
        }
      }
    } catch (error) {
      logger.error('初始化 Aria2 管理器失败:', error)
      // 向上抛出，让 AppLifecycle 显示用户友好的错误对话框
      throw error
    }
  }

  /**
   * 从设置中读取当前 RPC 连接参数。
   * 走**直读**：该密钥直接用于 RPC 鉴权，拿到过期密钥会导致连接失败。
   */
  private getRpcSettings(): { port: number; secret: string } {
    const settings = getSettingsFresh()
    const aria2Settings = settings.aria2 || {}
    return {
      port: Number(aria2Settings.port) || 6800,
      secret: String(aria2Settings.secret || '')
    }
  }

  public getManager(): Aria2ProcessManager | null {
    return this.aria2Manager
  }

  /**
   * 通过 RPC 让 aria2 立即把会话落盘（幂等）。成功返回 `{success:true}`，失败返回原因但不抛错。
   *
   * 供两处复用：
   * - `aria2-save-session` 通道（渲染层主动保存）；
   * - 「重启更新」这类**会跳过 before-quit** 的退出路径 —— `app.exit()` 不触发优雅关闭，
   *   不补这一刀的话未完成任务会从下次启动的恢复列表里消失（不是重新下载，而是不再出现）。
   *
   * @param timeoutMs 超时。默认 10s（会话文件可能较大，沿用既有实现）；
   *                  "退出前抢救"类调用可传更小的值，避免把退出流程拖太久。
   */
  public async saveSession(timeoutMs = 10000): Promise<{ success: boolean; error?: string }> {
    try {
      const { port, secret } = this.getRpcSettings()
      await callAria2Rpc({ port, secret, method: 'aria2.saveSession', timeoutMs })
      return { success: true }
    } catch (e) {
      return { success: false, error: String(e) }
    }
  }

  /**
   * 请求 aria2 关闭，但**不等待进程退出**（fire-and-forget）。
   *
   * 专用于"应用即将立即退出"的场景——目前是「重启更新」：它走 `app.exit(0)`，不触发 before-quit，
   * 而 Windows 上父进程退出不会回收子进程（且 `detached: false` 也不提供该语义），
   * 不主动停的话 **aria2 会成为孤儿进程继续占着 RPC 端口**，导致更新后的新版本启动引擎失败。
   *
   * 与 `setGracefulShutdown` 的钩子区别：那里要等进程退出（保证会话落盘、避免端口冲突），
   * 这里只把请求发出去——aria2 收到 shutdown 后会自行保存会话并退出，
   * 因此不拖慢退出流程，也不会与 NSIS 安装程序互等。
   */
  public requestShutdown(): void {
    // 置位后退出兜底不再强杀：aria2 收到 shutdown 会自行保存会话并退出，强杀会截断会话文件
    this.shutdownRequested = true
    const { port, secret } = this.getRpcSettings()
    void callAria2Rpc({ port, secret, method: 'aria2.shutdown', timeoutMs: 3000 })
      .then(() => logger.info('已请求 aria2 关闭（不等进程退出，用于立即退出场景）'))
      .catch((error) => {
        logger.warn('请求 aria2 关闭失败，aria2 可能残留并占用 RPC 端口：', error)
      })
  }

  /**
   * 将最新 Tracker 列表写入 aria2 配置文件（bt-tracker），供重启后生效。
   * 尝试通过 RPC 立即应用到运行中的 aria2，失败不影响写配置（下次重启生效）。
   */
  public applyTrackerList(csv: string): { success: boolean; error?: string } {
    if (!this.aria2Manager) return { success: false, error: 'Aria2 manager not initialized' }
    try {
      this.aria2Manager.saveGlobalOptionsToConfig({ 'bt-tracker': csv })
      // 尽力立即生效：bt-tracker 为运行时可变全局选项，失败时配置已持久化、重启后仍有效
      const { port, secret } = this.getRpcSettings()
      void callAria2Rpc({ port, secret, method: 'aria2.changeGlobalOption', params: [{ 'bt-tracker': csv }] })
        .catch(() => {})
      return { success: true }
    } catch (error) {
      return { success: false, error: error instanceof Error ? error.message : String(error) }
    }
  }

  public async stop() {
    if (this.aria2Manager && this.aria2Manager.isRunning()) {
      // stop 内部会先执行注入的 RPC 优雅关闭（保存会话），失败时回退信号关闭
      await this.aria2Manager.stop()
    }
  }

  public registerIpcHandlers() {
    // 统一经 ipcSecurity 的工厂注册：来源校验由工厂在结构上保证，
    // failureValue 逐一对应迁移前的失败形态（渲染层依赖这些语义）
    registerSecureHandler('aria2-start', async () => {
      if (!this.aria2Manager) await this.initialize()
      if (!this.aria2Manager) return { success: false, error: 'Aria2 manager not initialized' }
      const ok = await this.aria2Manager.start()
      // 失败时附带 aria2 stderr，便于设置页展示具体原因
      return { success: ok, error: ok ? undefined : (this.aria2Manager.getLastStderr() || 'Aria2 进程启动失败') }
    }, { getMainWindow: this.windowRef })

    registerSecureHandler('aria2-stop', async () => {
      if (!this.aria2Manager) return { success: true }
      await this.stop()
      return { success: true }
    }, { getMainWindow: this.windowRef })

    registerSecureHandler('aria2-restart', async () => {
      if (!this.aria2Manager) await this.initialize()
      if (!this.aria2Manager) return { success: false, error: 'Aria2 manager not initialized' }
      return { success: await this.aria2Manager.restart() }
    }, { getMainWindow: this.windowRef })

    // 失败态为 {isRunning:false,error}，不属于成功返回类型、也非标准 Unauthorized 形态，
    // 故显式标注返回类型（这也是唯一需要标注的通道）
    registerSecureHandler('aria2-status', (): ReturnType<Aria2ProcessManager['getProcessInfo']> | { isRunning: false; error: string } => {
      if (!this.aria2Manager) return { isRunning: false, error: 'Not initialized' }
      return this.aria2Manager.getProcessInfo()
    }, { getMainWindow: this.windowRef, failureValue: { isRunning: false, error: 'Unauthorized' } })

    registerSecureHandler('aria2-save-session', async () => await this.saveSession(), {
      getMainWindow: this.windowRef
    })

    registerSecureHandler('aria2-save-global-options', (event, options: Record<string, string | number>) => {
      if (!this.aria2Manager) return { success: false, error: 'Aria2 manager not initialized' }
      try {
        this.aria2Manager.saveGlobalOptionsToConfig(options || {})
        return { success: true }
      } catch (e) {
        return { success: false, error: String(e) }
      }
    }, { getMainWindow: this.windowRef })

    registerSecureHandler('aria2-update-config', async (event, config) => {
      if (!this.aria2Manager) await this.initialize()
      if (!this.aria2Manager) return { success: false, error: 'Aria2 manager not initialized' }

      // 入参规范化与校验，防止异常类型写入 store / 配置文件
      const port = Number(config?.port)
      if (!Number.isInteger(port) || port < MIN_PORT || port > MAX_PORT) {
        return { success: false, error: `Invalid port: ${config?.port}` }
      }
      const downloadDir = String(config?.downloadDir ?? '')
      // downloadDir 提供时必须为绝对路径，防止写入非法路径导致 aria2 启动失败；
      // 为空时保持原行为（由上游回退到默认下载目录）
      if (downloadDir && !path.isAbsolute(downloadDir)) {
        return { success: false, error: 'Invalid downloadDir: must be an absolute path' }
      }

      /**
       * 密钥清空意图判定：
       * 前端「连接预设尚未加载出密钥」时提交的 secret 为空，与用户"主动清空密钥"无法区分，
       * 若直接以空值落盘会静默关闭 RPC 访问保护（rpc-allow-origin-all 下浏览器可跨源调用）。
       * 因此仅当调用方显式声明 clearSecret 时才真正清空，否则保留原密钥。
       */
      // 直读：这是"读改写"路径，必须基于最新值计算，避免中间态或旧值影响判定
      const currentSettings = getSettingsFresh()
      const previousSecret = String(currentSettings.aria2?.secret || '')
      const incomingSecret = String(config?.secret ?? '')
      const clearSecret = config?.clearSecret === true
      const secret = incomingSecret || (clearSecret ? '' : previousSecret)

      const serializableConfig = {
        port,
        secret,
        downloadDir,
        enableRpc: config?.enableRpc === undefined ? true : Boolean(config.enableRpc),
        rpcAllowOriginAll: config?.rpcAllowOriginAll === undefined ? true : Boolean(config.rpcAllowOriginAll),
        autoStart: config?.autoStart === undefined ? true : Boolean(config.autoStart)
      }

      try {
        this.aria2Manager.updateConfig(serializableConfig)
      } catch (e) {
        // 配置文件写入失败时如实反馈，避免用户误以为保存成功
        const error = e instanceof Error ? e.message : String(e)
        logger.error('写入 aria2 配置失败:', error)
        return { success: false, error: `配置文件写入失败: ${error}` }
      }

      // 更新存储（显式标注 AppSettings 类型，避免对象字面量中的字面量类型被拓宽）
      // 仅当密钥值确实发生变化时才认为"用户显式管理了密钥"，
      // 避免表单里的密钥尚未加载（或与当前值相同）时误把自动生成能力永久关闭
      const secretChanged = secret !== previousSecret

      const updatedSettings: AppSettings = {
        ...currentSettings,
        aria2: {
          ...currentSettings.aria2,
          host: 'localhost',
          port: serializableConfig.port,
          protocol: 'http',
          secret,
          // 用户确实改动过密钥（含主动清空）：关闭自动生成，尊重显式选择；
          // 密钥未变则保持原标记不变
          secretAutogenerated: secretChanged
            ? false
            : currentSettings.aria2?.secretAutogenerated,
          path: '/jsonrpc',
          downloadDir: serializableConfig.downloadDir,
          autoStart: serializableConfig.autoStart
        }
      }
      // 写入口统一走 settingsAccessor：它负责加密落盘并同步刷新缓存（写与失效原子化）
      saveSettings(updatedSettings)
      if (!secret) {
        logger.warn('RPC secret 为空：rpc-allow-origin-all 下浏览器任意网页可跨源调用本机 RPC，建议设置密钥')
      }
      return { success: true }
    }, { getMainWindow: this.windowRef })
  }
}
