/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppSidebar: typeof import('./components/layout/AppSidebar.vue')['default']
    AppSwitch: typeof import('./components/AppSwitch.vue')['default']
    ConnectionDialog: typeof import('./components/dialogs/ConnectionDialog.vue')['default']
    DeleteTaskDialog: typeof import('./components/dialogs/DeleteTaskDialog.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDescriptions: typeof import('naive-ui')['NDescriptions']
    NDescriptionsItem: typeof import('naive-ui')['NDescriptionsItem']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NewTaskDialog: typeof import('./components/dialogs/NewTaskDialog.vue')['default']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/dialogs/SettingsDialog.vue')['default']
    SettingsPage: typeof import('./components/settings/SettingsPage.vue')['default']
    TaskBasicInfo: typeof import('./components/task/TaskBasicInfo.vue')['default']
    TaskBatchActions: typeof import('./components/task/TaskBatchActions.vue')['default']
    TaskCheckbox: typeof import('./components/TaskCheckbox.vue')['default']
    TaskDetailDrawer: typeof import('./components/dialogs/TaskDetailDrawer.vue')['default']
    TaskPeerInfo: typeof import('./components/task/TaskPeerInfo.vue')['default']
    TaskPiecesInfo: typeof import('./components/task/TaskPiecesInfo.vue')['default']
    TaskRowActions: typeof import('./components/task/TaskRowActions.vue')['default']
    TaskServerInfo: typeof import('./components/task/TaskServerInfo.vue')['default']
    TipLabel: typeof import('./components/settings/TipLabel.vue')['default']
    UpdateDialog: typeof import('./components/dialogs/UpdateDialog.vue')['default']
  }
}
